services:
  - type: web
    name: expense-tracker
    env: docker
    plan: free
    region: oregon   # match this with your DB region
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: expense-db
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
    autoDeploy: true

databases:
  - name: expense-db
    plan: free
    region: oregon   # same region as your web app
